export const CREDENTIAL_SBT_ABI = [
  {
    type: "function",
    name: "issueCredential",
    inputs: [
      { name: "student", type: "address" },
      { name: "docHash", type: "bytes32" },
      { name: "docType", type: "string" },
      { name: "cid", type: "string" },
    ],
    outputs: [{ name: "tokenId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "issueCredentialBatch",
    inputs: [
      { name: "students", type: "address[]" },
      { name: "docHashes", type: "bytes32[]" },
      { name: "docTypes", type: "string[]" },
      { name: "cids", type: "string[]" },
    ],
    outputs: [{ name: "tokenIds", type: "uint256[]" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "verifyCredential",
    inputs: [{ name: "docHash", type: "bytes32" }],
    outputs: [
      { name: "valid", type: "bool" },
      { name: "issuer", type: "address" },
      { name: "student", type: "address" },
      { name: "revoked", type: "bool" },
      { name: "docType", type: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "revokeCredential",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "presentMigration",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "destination", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptMigration",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "destination", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getCredential",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "issuer", type: "address" },
          { name: "student", type: "address" },
          { name: "docHash", type: "bytes32" },
          { name: "docType", type: "string" },
          { name: "cid", type: "string" },
          { name: "issuedAt", type: "uint256" },
          { name: "revoked", type: "bool" },
          { name: "migrationStatus", type: "uint8" },
          { name: "presentedTo", type: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isIssuer",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ownerOf",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokensOfOwner",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalIssuances",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "issuerCredentialCount",
    inputs: [{ name: "issuer", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "issuerFirstIssuedAt",
    inputs: [{ name: "issuer", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "issuerTemplateCount",
    inputs: [{ name: "issuer", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "issuerLastIssuedAt",
    inputs: [{ name: "issuer", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hashCount",
    inputs: [{ name: "docHash", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ISSUER_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "grantRole",
    inputs: [
      { name: "role", type: "bytes32" },
      { name: "account", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "hasRole",
    inputs: [
      { name: "role", type: "bytes32" },
      { name: "account", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "CredentialIssued",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "issuer", type: "address", indexed: true },
      { name: "student", type: "address", indexed: true },
      { name: "docHash", type: "bytes32", indexed: false },
      { name: "docType", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CredentialRevoked",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "issuer", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "MigrationPresented",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "student", type: "address", indexed: true },
      { name: "destination", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "MigrationAccepted",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "issuer", type: "address", indexed: true },
      { name: "destination", type: "address", indexed: true },
    ],
  },
] as const;
